### ISSUE TITLE
Unable to replay newly recorded macro

### ISSUE THREAD

**Issue by hauswij** [Microsoft/VS-Macros#14] opened 2016-05-13 15:27 UTC
When I try to create a macro, it says it can not save shortcut to-
C:\Users\hauswij\AppData\Local\Microsoft\VisualStudio\14.0\Macros\Macros

I created this directory by hand and it then can save to this dir with a file name Current.js
Next problem I ran into after this was trying to playback the macro.  Nothing happens.

I have VS 2015 update 1.

**Comment by justcla** [comment] 2016-05-13 19:18
Thanks for the feedback. Yes, this is related to Issue #7.
The Macros directories need to be initialized, and this occurs when the Macro Explorer is first opened.
We are working on a fix for this.

As for replaying the Macro, I found that sometimes it works on the second attempt.
We were able to get it to play after several attempts?
Are you able to reliably reproduce this?

**Comment by hauswij** [comment] 2016-05-13 19:32
I tried many times to replay the macro and never saw it run.
I tried copying current.js from
C:\Users\hauswij\AppData\Local\Microsoft\VisualStudio\14.0\Macros\Macros
To
C:\Users\hauswij\AppData\Local\Microsoft\VisualStudio\14.0\Macros
Thinking maybe there was a bug that accidently created 2 macros dirs and it was supposed to be just one.

**Comment by justcla** [comment] 2016-05-13 19:39
Thanks Jeff. Yes, we intend to create a Macros/Macros directory. It happens when the Macros Explorer is first opened. And that's where it will look for the Current.js.

Are you able to run any of the other macros?
(ie. Insert Date)

**Comment by justcla** [comment] 2016-05-13 19:39
Note: I'm renaming this issue.

**Comment by hauswij** [comment] 2016-05-13 19:48
I just found the samples, I was able to run the ones I clicked on.

**Comment by justcla** [comment] 2016-05-13 19:55
Sounds like we need to look deeper into this one.
If you email me at justcla@microsoft.com I'll work with you to see where the issue is.
Thanks!

**Comment by justcla** [comment] 2016-05-20 01:40
Fixed in version 1.2.0

**Closed by justcla** 2016-05-20 01:40 UTC

**Comment by hauswij** [comment] 2016-05-20 16:17
Works!  Thanks for fixing it.

**Comment by justcla** [comment] 2016-05-20 18:37
Excellent. Glad to hear.
You're welcome. :-)
